---
# tasks/configure-giteadb-database.yml
- block:
    - name: Install python dependencies.
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - python3-psycopg2
          - python3-pexpect
        state: present

    - name: Create PostgreSQL user for testing
      become: true
      postgresql_user:
        name: '{{gitea_db_user}}'
        password: '{{gitea_db_password}}'
        role_attr_flags: 'CREATEDB,NOSUPERUSER'
        login_host: '{{gitea_db_host}}'
        login_port: '{{gitea_db_host_port}}'
        login_password: '{{postgresql_password}}'
        login_user: '{{postgresql_user}}'

    - name: Create PostgreSQL database '{{gitea_db_name}}'
      become: true
      postgresql_db:
        name: '{{gitea_db_name}}'
        owner: '{{postgresql_user}}'
        state: present
        encoding: UTF-8
        template: template0
        login_host: '{{gitea_db_host}}'
        login_port: '{{gitea_db_host_port}}'
        login_password: '{{postgresql_password}}'
        login_user: '{{postgresql_user}}'

    - name: Grant {{gitea_db_user}} all privileges on database '{{gitea_db_name}}'
      become: true
      postgresql_privs:
        db: '{{gitea_db_name}}'
        objs: ALL_IN_SCHEMA
        privs: ALL
        role: '{{gitea_db_user}}'
        login_host: '{{gitea_db_host}}'
        login_port: '{{gitea_db_host_port}}'
        login_password: '{{postgresql_password}}'
        login_user: '{{postgresql_user}}'
