---
# Default variables for Gitea setup

# Gitea specific variables
gitea_version: "1.14.2"               # Version of Gitea to install
gitea_user: "gitea"                   # User under which Gitea will run
gitea_domain: "giteas.naiduden.dev"   # Domain for Gitea
gitea_http_port: 3000                 # HTTP port for Gitea
gitea_install_dir: "/opt/gitea"       # Installation directory for Gitea
gitea_data_dir: "/var/lib/gitea"      # Data directory for Gitea

# PostgreSQL specific variables
postgresql_version: "15"              # PostgreSQL version
postgresql_db: "giteadb"              # Database name for Gitea
postgresql_user: "gitea"              # PostgreSQL user for Gitea
postgresql_password: "Kites@123"      # Password for the PostgreSQL Gitea user
postgresql_host: "localhost"          # Host where PostgreSQL is running
postgresql_port: 5432                 # PostgreSQL port

# Other variables
gitea_secret_key: "generate_a_random_key" # Secret key for Gitea