---
- block:
    - name: Create PostgreSQL user for kea
      become: true
      become_user: postgres
      postgresql_user:
        state: present
        name: '{{ kea_db_user }}'
        password: '{{ kea_db_password }}'
        role_attr_flags: 'CREATEDB,NOSUPERUSER'

    - name: Create PostgreSQL database for kea
      become: true
      become_user: postgres
      postgresql_db:
        name: '{{ kea_db_name }}'
        owner: '{{ kea_db_user }}'
        state: present
        encoding: '{{ postgresql_encoding }}'
        lc_collate: '{{ postgresql_locale }}'
        lc_ctype: '{{ postgresql_locale }}'
        template: template0

    - name: Make kea user as owner of kea database
      become: true
      become_user: postgres
      postgresql_privs:
        db: '{{ kea_db_name }}'
        privs: 'ALL'
        type: database
        role: '{{ kea_db_user }}'
