---
- block:
    - name: Ensure dnsmasq is installed
      package:
        name: dnsmasq
        state: present

    - name: Backup dnsmasq.conf
      copy:
        src: /etc/dnsmasq.conf
        dest: /etc/dnsmasq.conf.bak
        remote_src: yes

    - name: Copy dnsmasq.conf template and overwrite the original
      template:
        src: dnsmasq.conf.j2
        dest: /etc/dnsmasq.conf
        owner: root
        group: root
        mode: 0644
      notify: restart dnsmasq

    - name: Add {{dhcp_server_ip}} to /etc/resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        line: 'nameserver {{dhcp_server_ip}}'
        state: present
      notify: restart dnsmasq
