---
- block:
    - name: Ensure apt cache is up to date
      apt:
        update_cache: yes

    - name: Apt Upgrade
      apt:
        upgrade: dist
        update_cache: yes

    - name: Ensure the locale exists
      locale_gen:
        name: en_US.UTF-8
        state: present

    - name: Set as default locale
      lineinfile:
        path: /etc/default/locale
        regexp: '^LANG='
        line: 'LANG=en_US.UTF-8'
        state: present

    - name: Install dependencies
      apt:
        name: '{{ item }}'
        state: present
      with_items:
        - libpq-dev
        - python3-psycopg2
        - sudo

    - name: Install PostgreSQL
      apt:
        name: '{{ item }}'
        state: present
      with_items:
        - postgresql-{{ postgresql_version }}
        - postgresql-contrib-{{ postgresql_version }}

    - name: Ensure PostgreSQL service is running
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Backup the original configuration file
      copy:
        src: /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
        dest: /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf.bak
        remote_src: yes

    - name: Ensure the conf.d folder exists
      file:
        path: /etc/postgresql/{{ postgresql_version }}/main/conf.d
        state: directory
        owner: postgres
        group: postgres
        mode: 0755

    - name: Copy the new configuration template file to conf.d folder
      template:
        src: postgres_shared.conf.j2
        dest: /etc/postgresql/{{ postgresql_version }}/main/conf.d/postgres_shared.conf
        owner: postgres
        group: postgres
        mode: 0644
      notify: restart postgresql

    - name: Backup the original pg_hba.conf file
      copy:
        src: /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
        dest: /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf.bak
        remote_src: yes

    - name: Ensure MD5 authentication for all users
      ansible.builtin.lineinfile:
        path: /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
        regexp: '^local\s+all\s+all\s+'
        line: 'local   all             all                                     md5'
        owner: postgres
        group: postgres
        mode: '0600'
      notify: reload postgresql

    - name: Apt Cleanup
      apt:
        autoclean: yes
        autoremove: yes
        state: latest

  become_method: sudo
  become_user: root
  remote_user: root
