---
- name: import variable checks tasks
  import_tasks: checks.yml
  tags:
    - gitea
    - gitea_act_runner
    - checks

- name: import act-runner configuration tasks
  import_tasks: act-runner.yml
  become: true
  tags:
    - gitea
    - gitea_act_runner

- name: import ansible facts configuration tasks
  import_tasks: fact.yml
  become: true
  tags:
    - gitea
    - gitea_act_runner
