---
gitea_http_domain: 192.168.30.60
gitea_root_url: http://192.168.30.60:80
gitea_protocol: http
gitea_http_listen: 192.168.30.60
gitea_http_port: 80
gitea_offline_mode: true

gitea_app_name: 'Gitea - Local'
