---
gitea_http_domain: 192.168.30.42
gitea_root_url: http://192.168.30.42:80
gitea_protocol: http
gitea_http_listen: 192.168.30.42
gitea_http_port: 80
gitea_offline_mode: true

gitea_app_name: 'Gitea - Prod'

# For terraform
environmenttype: 'prod'
needed_vms: ['pxbackupserver']

# host node proxmox details
proxmox_api_endpoint_url: 'https://192.168.1.11:8006/'
proxmox_api_user: 'root@pam'
proxmox_api_password: 'Float12345678'
proxmox_tls_insecure: true
proxmox_node: 'spmhampi'

storage_pool: 'proxthin'
nas_storage_pool: 'nasvmdrives'
interface_bridge: 'vmbr2'
template_file_location_id: 'nasisos:vztmpl/debian-12-standard_12.2-1_amd64.tar.zst'

# gitea server config values
gitea_vm_prefix: ${environmenttype}
gitea_vm_name: 'gitea'
gitea_vm_description: 'Gitea for source control management and CI/CD'
gitea_server_ip: '192.168.80.13/24'
gitea_server_gateway: '192.168.80.1'

# pihole server config values
pihole_vm_prefix: ${environmenttype}
pihole_vm_name: 'pihole'
pihole_vm_description: 'pihole server for development'
pihole_server_ip: '192.168.80.14/24'
pihole_server_gateway: '192.168.80.1'

# dev lxc server config values
dev_lxc_server_ip: '192.168.80.15/24'
dev_lxc_server_gateway: '192.168.80.1'
#

# proxmox backup server
pxbackup_vm_prefix: ${environmenttype}
pxbackup_vm_name: 'pxbackupserver'
pxbackup_vm_description: 'Proxmox backup server for dev'
pxbackup_server_ip: '192.168.30.45/24'
pxbackup_server_gateway: '192.168.80.1'
