---
gitea_http_domain: gitea.apps.naiduden.dev
gitea_root_url: https://gitea.apps.naiduden.dev
gitea_protocol: https
gitea_http_listen: gitea.apps.naiduden.dev
gitea_http_port: 80
gitea_offline_mode: true

gitea_app_name: 'Gitea - Prod'

gitea_db_type: postgres
gitea_db_host: 192.168.30.44
gitea_db_host_port: 5432
gitea_db_name: giteadb
gitea_db_user: gitea
gitea_db_password: Kites@123
gitea_db_ssl: disable
gitea_db_path: '{{ gitea_home }}/data/gitea.db'

gitea_ssh_listen: gitea.apps.naiduden.dev
gitea_ssh_domain: gitea.apps.naiduden.dev
gitea_start_ssh: true
gitea_ssh_port: 2222

# PostgreSQL specific variables
postgresql_user: postgres
postgresql_password: 1Uh4$f^Vrtju^J

# For terraform
environmenttype: 'prod'
# needed_vms: ['backup-pxb', 'db-postgres']

# host node proxmox details
proxmox_api_endpoint_url: 'https://192.168.1.11:8006/'
proxmox_api_user: 'root@pam'
proxmox_api_password: 'Float12345678'
proxmox_tls_insecure: true
proxmox_node: 'spmhampi'
proxmox_node_with_clone: 'spmhampi'
proxmox_node_for_core_services: 'kishkindha-pcli'

storage_pool: 'proxthin'
nas_storage_pool: 'nasvmdrives'
snippets_storage_pool: 'nasbackups'
interface_bridge: 'vmbr2'
template_file_location_id: 'nasisos:vztmpl/debian-12-standard_12.2-1_amd64.tar.zst'
supported_disk_format_raw: 'raw'
supported_disk_format_qcow2: 'qcow2'

# gitea server config values
# gitea_vm_suffix: 'prod'
gitea_vm_name: 'gitea-prod' # index will added in terraform code
# gitea_host_name_inside_vm: 'gitea' # index will added in terraform code
gitea_number_of_instances: 1
gitea_vm_description: 'Gitea for source control management and CI/CD'
gitea_network_interface_details:
  first_interface:
    ip: '192.168.30.45/24'
    gateway: '192.168.30.1'
    vlan_id: 30
    interface_bridge: 'vmbr2'

# pihole server config values
pihole_vm_suffix: 'prod' # index will added in terraform code
pihole_vm_name: 'pihole-prod' # index will added in terraform code
pihole_host_name_inside_vm: 'pihole' # index will added in terraform code
pihole_number_of_instances: 0
pihole_vm_description: 'pihole server for development'
pihole_network_interface_details:
  first_interface:
    ip: '192.168.30.51/24'
    gateway: '192.168.30.1'
    vlan_id: 30
    interface_bridge: 'vmbr2'

# dev lxc server config values
dev_lxc_vm_name: 'dev-debian' # index will added in terraform code
dev_lxc_host_name_inside_vm: 'devdebian' # index will added in terraform code
dev_lxc_number_of_instances: 0
dev_lxc_vm_description: 'development box for coding'
dev_lxc_server_ip: '192.168.30.15/24'
dev_lxc_server_gateway: '192.168.30.1'
dev_lxc_network_interface_details:
  first_interface:
    ip: '192.168.30.15/24'
    gateway: '192.168.30.1'
    vlan_id: 80
    interface_bridge: 'vmbr0'
#

# proxmox backup server
pxbackup_vm_suffix: 'prod'
pxbackup_vm_name: 'backup-pxb-prod' # index will added in terraform code
pxbackup_host_name_inside_vm: 'backuppxb' # index will added in terraform code
pxbackup_number_of_instances: 1
pxbackup_vm_description: 'Proxmox backup server for dev'
pxbackup_network_interface_details:
  first_interface:
    ip: '192.168.30.46/24'
    gateway: '192.168.30.1'
    vlan_id: 30
    interface_bridge: 'vmbr2'
  second_interface:
    ip: '192.168.80.46/24'
    gateway: '192.168.80.1'
    vlan_id: 80
    interface_bridge: 'vmbr2'

# postgres server
postgres_vm_suffix: 'prod'
postgres_vm_name: 'db-postgres-prod' # index will added in terraform code
postgres_host_name_inside_vm: 'dbpostgres' # index will added in terraform code
postgres_number_of_instances: 1
postgres_vm_description: 'Postgres server for dev'
postgres_network_interface_details:
  first_interface:
    ip: '192.168.30.44/24'
    gateway: '192.168.30.1'
    vlan_id: 30
    interface_bridge: 'vmbr2'

# doceker core server
docker_core_vm_suffix: 'prod'
docker_core_vm_name: 'docker-coreservices-prod' # index will added in terraform code
docker_core_vm_name_inside_vm: 'dockercoreservices' # index will added in terraform code
docker_core_vm_number_of_instances: 1
docker_core_vm_cpu_cores: 4
docker_core_vm_memory: 6144
docker_core_vm_description: 'Docker with core servevices like DNS/DHCP and CI/CD'
docker_core_vm_storage_disk_type: 'raw'
docker_core_vm_network_interface_details:
  first_interface:
    ip: '192.168.30.47/24'
    gateway: '192.168.30.1'
    vlan_id: 30
    interface_bridge: 'vmbr2'

# docker core services overrides
docker_core:
  services:
    cf_domain_for_core_apps: 'core.naiduden.dev'
    cf_domain_for_all_apps: 'apps.naiduden.dev'
    cf_api_key: 'e436d5c4f61e4cdb31d54b7e4f35e54c1683e'
    cf_api_email: 'deepakn.dev@gmail.com'
    pf_sense_domain: 'pf.naiduden.dev'
    dns_challenge_subnet: '192.168.30.0/24'
    dns_challenge_gateway: '192.168.30.1'
    dns_challenge_ip_range: '192.168.30.80/28'
    dns_challenge_static_ip: '192.168.30.81'
  hosted_services:
    pihole_static_ip_address: '192.168.30.82'
  vm_details:
    suffix: 'stage'
    name: 'docker-coreservices-stage' # index will added in terraform code
    name_inside_vm: 'dockercoreservices' # index will added in terraform code
    number_of_instances: 1
    cpu_cores: 4
    memory: 6144
    description: 'Docker with core servevices like DNS/DHCP and CI/CD'
    network_interface_details:
      first_interface:
        ip: '192.168.30.47/24'
        gateway: '192.168.30.1'
        vlan_id: 80
        interface_bridge: 'vmbr2'
# gitea runner server
gitea_runner_vm:
  host_details:
    proxmox_node: 'spmhampi'
    proxmox_node_with_clone: 'spmhampi'
    clone_id: '5000'
  vm_details:
    suffix: 'prod' # index will added in terraform code
    description: 'Gitea act runner to run the jobs'
    name: 'gitea-runner-prod' # index will added in terraform code
    host_name_inside_vm: 'gitearunnerprod' # index will added in terraform code
    number_of_instances: 1
    cpu_cores: 2
    memory: 2048
    storage_pool: 'proxthin'
    os_storage_disk_type: 'raw'
    network_interface_details:
      first_interface:
        ip: '192.168.30.48/24'
        gateway: '192.168.30.1'
        vlan_id: 30
        interface_bridge: 'vmbr2'

# k8s control plane server
k8s_cp_vm:
  host_details:
    proxmox_node: 'lepakshi-lenovomini'
    proxmox_node_with_clone: 'lepakshi-lenovomini'
    clone_id: '5000'
  vm_details:
    suffix: 'stage' # index will added in terraform code
    description: 'K8s control plane server'
    name: 'k8s-cp-stage' # index will added in terraform code
    host_name_inside_vm: 'k8scpstage' # index will added in terraform code
    number_of_instances: 0
    cpu_cores: 2
    memory: 2048
    storage_pool: 'proxthin'
    os_storage_disk_type: 'qcow2'
    network_interface_details:
      first_interface:
        ip: '192.168.80.55/24'
        gateway: '192.168.80.1'
        vlan_id: 80
        interface_bridge: 'vmbr0'

k8s_wn_vm:
  host_details:
    proxmox_node: 'lepakshi-lenovomini'
    proxmox_node_with_clone: 'lepakshi-lenovomini'
    clone_id: '5000'
  vm_details:
    suffix: 'stage' # index will added in terraform code
    description: 'K8s worker node server'
    name: 'k8s-wn-stage' # index will added in terraform code
    host_name_inside_vm: 'k8swnstage' # index will added in terraform code
    number_of_instances: 0
    cpu_cores: 2
    memory: 2048
    storage_pool: 'proxthin'
    os_storage_disk_type: 'qcow2'
    network_interface_details:
      first_interface:
        ip: '192.168.80.56/24'
        gateway: '192.168.80.1'
        vlan_id: 80
        interface_bridge: 'vmbr0'

proxy_ingress_lxc:
  host_details:
    proxmox_node: 'lepakshi-lenovomini'
    proxmox_node_with_clone: 'lepakshi-lenovomini'
    clone_id: '5000'
  lxc_details:
    suffix: 'stage' # index will added in terraform code
    description: 'Proxy ingress server'
    name: 'proxyingresslxc' # index will added in terraform code
    host_name_inside_vm: 'proxyingresslxc' # index will added in terraform code
    number_of_instances: 0
    cpu_cores: 2
    memory: 1024
    storage_pool: 'proxthin'
    os_storage_disk_type: 'raw'
    os_storage_disk_size: '10'
    network_interface_details:
      first_interface:
        ip: '192.168.80.57/24'
        gateway: '192.168.80.1'
        vlan_id: 80
        interface_bridge: 'vmbr0'

# gitea runner server
dev_debian_vm:
  host_details:
    proxmox_node: 'spmhampi'
    proxmox_node_with_clone: 'spmhampi'
    clone_id: '5000'
  vm_details:
    suffix: 'prod' # index will added in terraform code
    description: 'Debian development box for coding'
    name: 'debian-dev-server' # index will added in terraform code
    host_name_inside_vm: 'debiandevserver' # index will added in terraform code
    number_of_instances: 1
    cpu_cores: 4
    memory: 8192
    storage_pool: 'nasvmdrives'
    os_storage_disk_type: 'raw'
    network_interface_details:
      first_interface:
        ip: '192.168.80.80/24'
        gateway: '192.168.80.1'
        vlan_id: 80
        interface_bridge: 'vmbr2'
