---
- name: Get the timezone of the system
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Get the timezone of the system
      command: date +%Z
      register: timezone
      changed_when: false

    - name: Output the timezone of the system
      debug:
        msg: 'The timezone of the system is {{ timezone.stdout }}'

    - name: Set timezone to America/Los_Angeles
      command: timedatectl set-timezone America/Los_Angeles
      when: timezone.stdout != 'PDT'
      changed_when: timezone.stdout != 'PDT'
