---
- hosts: codeserver
  become: yes
  become_method: sudo
  become_user: root
  remote_user: root

  tasks:
    - name: Update the system
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install basic packages
      apt:
        name: '{{ item }}'
        state: present
      with_items:
        - gnupg2
        - curl
        - git
        - wget
        - unzip
        - build-essential

    - name: Install Ansible and Python
      apt:
        name: '{{ item }}'
        state: present
      with_items:
        - python3
        - python3-pip
        - python3-venv
        - libssl-dev
        - libffi-dev
        - ansible
        - virtualenv
        - ansible-lint

    - name: Install Terraform dependencies
      apt:
        name:
          - unzip
          - wget
          - gnupg
          - software-properties-common
        state: present

    - name: Remove existing HashiCorp GPG key
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: absent

    - name: Add HashiCorp GPG key
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        keyring: /usr/share/keyrings/hashicorp-archive-keyring.gpg

    - name: Add HashiCorp repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg]
          https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
        filename: hashicorp

    - name: Apt Uppdate
      apt:
        update_cache: true

    - name: Install Terraform
      apt:
        name: terraform
        state: present

    - name: Install Node.js and npm
      apt:
        name: '{{ item }}'
        state: present
      with_items:
        - nodejs
        - npm

    - name: Install zsh
      apt:
        name: '{{ item }}'
        state: present
      with_items:
        - zsh
        - fonts-powerline

    - name: Download Oh my zsh to tmp folder
      get_url:
        url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/install_oh_my_zsh.sh

    - name: Delete oh-my-zsh folder if it exists
      become_user: dnndev
      become_method: sudo
      shell: rm -rf /home/dnndev/.oh-my-zsh

    - name: Install Oh My Zsh for dnndev
      become_user: dnndev
      become_method: sudo
      command: sh /tmp/install_oh_my_zsh.sh --unattended

    - name: Set zsh as default shell
      become_user: dnndev
      become_method: sudo
      shell: chsh -s $(which zsh)

    - name: Delete powerlevel10k and clone it again
      become_user: dnndev
      become_method: sudo
      shell: rm -rf ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k && git clone https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k

    - name: Delete zsh-autosuggestions and clone it again
      become_user: dnndev
      become_method: sudo
      shell: rm -rf  ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions && git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

    - name: Delete zsh-syntax-highlighting and clone it again
      become_user: dnndev
      become_method: sudo
      shell: rm -rf ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting && git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

    - name: Update .zshrc for root using sed to replace the default theme
      become_user: dnndev
      become_method: sudo
      shell: sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="powerlevel10k\/powerlevel10k"/' ~/.zshrc

    - name: Update .zshrc for dnndev
      become_user: dnndev
      become_method: sudo
      lineinfile:
        path: ~/.zshrc
        line: '{{ item }}'
      with_items:
        - 'ZSH_THEME="powerlevel10k/powerlevel10k"'
        - 'plugins=(git zsh-autosuggestions zsh-syntax-highlighting)'
        - 'source $ZSH/oh-my-zsh.sh'

    - name: Install nvm
      shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
