---
- name: Install Docker on Ubuntu
  hosts: docker-core-services
  become: true
  gather_facts: true
  vars:
    arch_mapping: # Map ansible architecture {{ ansible_architecture }} names to Docker's architecture names
      x86_64: amd64
      aarch64: arm64
    ansible_ssh_pipelining: true
  roles:
    - role: docker-core-services
