---
- name: Install and configure Terraform
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

  tasks:
    - name: Install Terraform dependencies
      apt:
        name:
          - unzip
          - wget
          - gnupg
          - software-properties-common
        state: present

    - name: Remove existing HashiCorp GPG key
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: absent

    - name: Add HashiCorp GPG key
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        keyring: /usr/share/keyrings/hashicorp-archive-keyring.gpg

    - name: Add HashiCorp repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg]
                  https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
        filename: hashicorp

    - name: apt update
      apt:
        update_cache: yes

    - name: Install Terraform
      apt:
        name: terraform
        state: present
