---
- name: Restart postgresql
  service:
    name: '{{ postgresql_service_name }}'
    state: restarted
    enabled: yes
    daemon_reload: yes
  listen: restart postgresql

- name: Reload postgresql
  service:
    name: '{{ postgresql_service_name }}'
    state: reloaded
    enabled: yes
    daemon_reload: yes
  listen: reload postgresql

- name: Restart apache2
  service:
    name: apache2
    state: restarted
    enabled: yes
    daemon_reload: yes
  listen: restart apache2

- name: Restart httpd
  service:
    name: httpd
    state: restarted
    enabled: yes
    daemon_reload: yes
  listen: restart httpd
