---
- name: Install and configure pgAdmin
  vars:
    pgadmin_repo: >-
      deb [signed-by=/usr/share/keyrings/packages-pgadmin-org.gpg]
      https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/{{ ansible_distribution_release | lower }} pgadmin4 main
  block:
    - name: Install dependencies
      ansible.builtin.apt:
        name: '{{ item }}'
        state: latest
        update_cache: yes
      loop:
        - gnupg2
        - libpq-dev
        - libgmp3-dev

    - name: Download pgAdmin GPG key
      ansible.builtin.get_url:
        url: https://www.pgadmin.org/static/packages_pgadmin_org.pub
        dest: /tmp/packages_pgadmin_org.pub
        mode: '0644'

    - name: Import pgAdmin GPG key
      ansible.builtin.shell:
        cmd: gpg --dearmor -o /usr/share/keyrings/packages-pgadmin-org.gpg /tmp/packages_pgadmin_org.pub
        creates: /usr/share/keyrings/packages-pgadmin-org.gpg

    - name: Output the pgadmin_repo
      ansible.builtin.debug:
        var: pgadmin_repo

    - name: Add pgAdmin repository
      ansible.builtin.apt_repository:
        repo: '{{ pgadmin_repo }}'
        state: present
        update_cache: yes
        filename: 'pgadmin4'

    - name: Apt update
      ansible.builtin.apt:
        update_cache: yes

    - name: Install pgAdmin web mode
      ansible.builtin.apt:
        name: pgadmin4-web
        state: latest
        update_cache: yes

    - name: Configure pgAdmin4 (setup web mode)
      become: true
      become_method: sudo
      become_user: root
      remote_user: root
      environment:
        PGADMIN_SETUP_EMAIL: '{{ pgadmin4_admin_email }}'
        PGADMIN_SETUP_PASSWORD: '{{ pgadmin4_admin_password }}'
      command:
        cmd: '{{ pgadmin4_home_dir }}/bin/setup-web.sh --yes'
