---
# tasks/main.yml
- name: Install PostgreSQL
  import_tasks: setup-postgresql.yml

- name: Configure test database
  import_tasks: configure-test-database.yml
  when: postgresql_db is defined

- name: Install pgAdmin
  import_tasks: install-pgAdmin.yml
