---
# tasks file for PostgreSQL role

- block:
    - name: Ensure the locale exists
      locale_gen:
        name: en_US.UTF-8
        state: present

    - name: Set as default locale
      lineinfile:
        path: /etc/default/locale
        regexp: '^LANG='
        line: 'LANG=en_US.UTF-8'
        state: present

    - name: Ensure apt cache is up to date
      apt:
        update_cache: yes

    - name: Instal dependencies for PostgreSQL
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: true
      loop:
        - libpq-dev
        - python3-psycopg2

    - name: Install PostgreSQL packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - postgresql-{{ postgresql_version }}
        - postgresql-contrib-{{ postgresql_version }}

    - name: Ensure PostgreSQL service is running
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Copy PostgreSQL configuration template
      template:
        src: postgresql.conf.j2
        dest: /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
        owner: postgres
        group: postgres
        mode: '0644'
      notify: Restart postgresql

    - name: Apt Cleanup
      apt:
        autoclean: yes
        autoremove: yes
        state: latest

  # - name: Copy PostgreSQL configuration template
  #   template:
  #     src: postgresql.conf.j2
  #     dest: /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
  #   notify: restart postgresql
  become_method: sudo
  become_user: root
  remote_user: dnndev