---
- name: Configure all proxmox hosts
  hosts: proxmox_hosts
  become: yes

  tasks:
    - name: Remove enterprise subscription list.
      file:
        path: '/etc/apt/sources.list.d/{{ item }}'
        state: absent
      with_items:
        - pve-enterprise.list.dpkg-dist
        - pve-enterprise.list
      tags:
        - apt

    - name: Ensure ceph.list Repository is absent
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/ceph.list
        regexp: '^deb'
        line: '#deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise'
        state: present

    - name: Create no subscription update list.
      copy:
        dest: /etc/apt/sources.list.d/pve-no-subscription.list
        content: deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription
        mode: 0644
      tags:
        - apt

    - name: Update and upgrade all packages to the latest version
      ansible.builtin.apt:
        update_cache: true
        upgrade: 'yes'

    - name: Install commonly used and helpful packages
      ansible.builtin.apt:
        name:
          - ifupdown2
          - vim
          - htop
          - net-tools
          - sudo
          - curl
          - gnupg
        state: present

    - name: Set timezone
      ansible.builtin.include_tasks:
        file: ./set-timezone.yml
